# Generated by Django 5.2 on 2025-08-27 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (5, "⭐️⭐️⭐️⭐️⭐️ (5 sao)"),
                            (4, "⭐️⭐️⭐️⭐️ (4 sao)"),
                            (3, "⭐️⭐️⭐️ (3 sao)"),
                            (2, "⭐️⭐️ (2 sao)"),
                            (1, "⭐️ (1 sao)"),
                        ],
                        default=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="company.company",
                    ),
                ),
            ],
        ),
    ]
