# Generated by Django 5.2 on 2025-08-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (5, "⭐️⭐️⭐️⭐️⭐️ (5 sao)"),
                    (4, "⭐️⭐️⭐️⭐️ (4 sao)"),
                    (3, "⭐️⭐️⭐️ (3 sao)"),
                    (2, "⭐️⭐️ (2 sao)"),
                    (1, "⭐️ (1 sao)"),
                ],
                default=5,
            ),
        ),
    ]
