# Generated by Django 5.2 on 2025-08-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_company_created_at_company_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/image/"),
        ),
    ]
